version: '3.6'

volumes:
  grafana_config:

services:
  grafana:
    image: grafana/grafana:8.2.6
    env_file: configuration.env
    user: '1066247'
    ports:
      - '3000:3000'
    volumes:
      - grafana_config:/etc/grafana
      - ./volumes/grafana:/var/lib/grafana
  influxdb:
    image: influxdb:1.8-alpine
    env_file: configuration.env
    ports:
      - '8086:8086'
    volumes:
      - ./volumes/influxdb:/var/lib/influxdb
  oracle:
    image: oracleinanutshell/oracle-xe-11g:latest
    env_file: configuration.env
    ports:
      - 1521:1521
      - 5500:5500
    volumes:
      - ./volumes/oracle:/opt/oracle/oradata
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04
    env_file: configuration.env
    ports:
      - 1433:1433
    volumes:
      - ./volumes/mssql:/var/opt/mssql/data
